[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "gv-snapshot"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
python = ">=3.10,<3.13"
jupyterlab = ">=4.2.5,<5"
pyld = ">=2.0.4,<3"
jsonpath-ng = ">=1.6.1,<2"
jupyterlab-git = ">=0.50.1,<0.51"

[pypi-dependencies]
phenopackets = "*"
hpo3 = "*"
